function model = train_model(X,Y,model_name)

switch model_name

    case "RF"

        model = TreeBagger(100, X, Y, ...
            "Method", "classification", ...
            "SampleWithReplacement", "on", ...
            "InBagFraction", 1, ...
            "OOBPrediction","on", ...
            "NumPredictorsToSample", 4, ...
            "MinLeafSize", 1);

    case "SVM"

        model = fitcsvm(X, Y, ...
            "KernelFunction", "gaussian", ...
            "BoxConstraint", 1, ...
            "KernelScale", "auto",...
            "Solver", "SMO", ...
            "Standardize",false, ...
            "Verbose",1);


    case "LSTM"

        %         model = ...

end


end